name: puzzles_arcade
description: A collection of fun and challenging logic puzzles.
publish_to: 'none'
version: 2.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Utilities
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  
  
  # UI & Animations
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0

  # Collection utilities
  collection: ^1.17.0

  # Audio
  audioplayers: ^6.0.0

  # Firebase for Daily Challenges
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^6.0.0 # Added for Google Sign-In
  build_runner: ^2.4.13

  # Monetization
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.0 # Added for in-app purchases


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Your icon logo without a background
  adaptive_icon_background: "#FFFFFF" # A color for the background
  adaptive_icon_foreground: "assets/icon/icon.png" # Your icon logo